"""
Synthesis phase for Deliberative Council.

Uses an impartial model from a DIFFERENT family than the debaters
to weigh arguments and produce a final structured report with
full pipeline trace and cost attribution.
"""

from __future__ import annotations

import json
import logging

from council.config import CouncilConfig
from council.models import LLMClient, ModelRegistry
from council.types import (
    Complexity,
    ConsensusLevel,
    DebateState,
    EvidenceReport,
    FinalReport,
    KeyPoint,
    MissionBrief,
    ModelUsage,
    PipelineTrace,
)

logger = logging.getLogger(__name__)


# ── Synthesis Prompt ─────────────────────────────────────────────────────

SYNTHESIS_PROMPT = """You are an impartial Synthesizer for a multi-AI debate system. Your job is to weigh the arguments from a structured debate and produce a fair, comprehensive final report.

## Question
{question}

## Debate Summary
{debate_summary}

## Research Evidence
{evidence_summary}

## Instructions
Produce a final synthesis that:
1. Weighs arguments based on evidence quality, logical coherence, and convergence
2. Does NOT simply pick the majority view — a well-argued minority position may be correct
3. Preserves genuine disagreements in dissenting_views
4. Assigns consensus levels: "strong" (all agree), "moderate" (most agree), "contested" (significant disagreement)
5. Notes any futility or unresolved issues

You must respond with a JSON object:
{{
  "answer": "Your synthesized answer in markdown format. This should be comprehensive and nuanced.",
  "key_points": [
    {{
      "point": "A key finding",
      "consensus": "strong" | "moderate" | "contested",
      "evidence": ["source URLs if available"],
      "dissent": "Who disagrees and why, or null"
    }}
  ],
  "dissenting_views": ["description of each unresolved disagreement"],
  "research_sources": ["all source URLs from evidence"],
  "futility_notes": "Any notes about debate futility or null"
}}

## Important Rules
- You must be impartial — do not favor arguments from any particular model family
- Preserve dissenting views honestly — do not paper over genuine disagreements
- Weight sourced evidence above inferred or judgment-tagged findings
- If the debate was marked as futile, acknowledge this in your notes
- Your answer should be thorough but clear, using markdown formatting

Respond ONLY with the JSON object."""


# ── Synthesis Phase ──────────────────────────────────────────────────────


async def run_synthesis(
    brief: MissionBrief,
    evidence: list[EvidenceReport],
    debate_state: DebateState,
    client: LLMClient,
    registry: ModelRegistry,
    config: CouncilConfig | None = None,
) -> FinalReport:
    """Synthesize the final report using an impartial model from a different family.

    The synthesizer must come from a different model family than any debater
    to ensure impartiality. This prevents the synthesizer from having a
    built-in affinity for arguments generated by its own family.

    Args:
        brief: The Mission Brief from the Scout phase.
        evidence: Research evidence reports.
        debate_state: The final state of the debate.
        client: LLM client for making completion calls.
        registry: Model registry for model selection.
        config: Council configuration.

    Returns:
        A FinalReport with the synthesized answer and full pipeline trace.
    """
    cfg = config or CouncilConfig()

    # Select synthesizer from a different family than debaters
    synthesizer_model = _select_synthesizer(debate_state, registry, cfg)

    logger.info(f"Synthesizer using model: {synthesizer_model}")

    # Build debate summary
    debate_summary = _build_debate_summary(debate_state)
    evidence_summary = _build_evidence_summary(evidence)

    # Generate synthesis
    prompt = SYNTHESIS_PROMPT.format(
        question=brief.question,
        debate_summary=debate_summary,
        evidence_summary=evidence_summary,
    )

    try:
        response_text, tokens = await client.complete(
            model_id=synthesizer_model,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=4096,
            temperature=0.3,
        )
    except Exception as e:
        logger.error(f"Synthesis generation failed: {e}")
        return _fallback_report(brief, debate_state, evidence, f"Synthesis failed: {str(e)[:200]}")

    # Parse the synthesis
    report = _parse_synthesis(response_text, brief, debate_state, evidence)

    # Build pipeline trace
    report.pipeline_trace = _build_pipeline_trace(
        brief=brief,
        evidence=evidence,
        debate_state=debate_state,
        synthesis_model=synthesizer_model,
        registry=registry,
        synthesis_tokens=tokens,
    )

    # Generate raw markdown
    report.raw_markdown = _generate_markdown(report)

    return report


def _select_synthesizer(
    debate_state: DebateState,
    registry: ModelRegistry,
    config: CouncilConfig,
) -> str:
    """Select a synthesizer model from a different family than any debater.

    The synthesizer must be impartial, so it comes from a family not
    represented in the debate.
    """
    from council.types import ModelTier

    # Find which families were used in the debate
    debater_families = set()
    if debate_state.rounds:
        for round_result in debate_state.rounds:
            for pos in round_result.positions:
                # We can't directly know the family from Position, so we check
                # the model registry for what was likely used
                pass

    # Get all model families from the registry
    available_families = registry.available_families()

    # Prefer premium or mid-tier from a family not in the debater set
    # For now, we select the best available model from any family,
    # with preference for premium tier
    if config.model_overrides and "synthesizer" in config.model_overrides:
        override = config.model_overrides["synthesizer"]
        model = registry.get(override)
        if model and model.is_available:
            return override

    # Try premium models first
    premium_models = registry.models_by_tier(ModelTier.PREMIUM)
    if premium_models:
        if config.family:
            family_match = [m for m in premium_models if m.family == config.family]
            if family_match:
                return family_match[0].model_id
        return premium_models[0].model_id

    # Fallback to mid-tier
    mid_models = registry.models_by_tier(ModelTier.MID)
    if mid_models:
        return mid_models[0].model_id

    # Last resort: first available model
    available = registry.available_models()
    return available[0].model_id if available else "openai/gpt-4.1-mini"


def _build_debate_summary(debate_state: DebateState) -> str:
    """Build a structured summary of the debate for the synthesizer."""
    lines = []
    lines.append(f"Total rounds: {len(debate_state.rounds)}")
    lines.append(f"Resolution: {debate_state.resolution_reason or 'N/A'}")
    lines.append("")

    for round_result in debate_state.rounds:
        lines.append(f"### Round {round_result.round_number}")
        for pos in round_result.positions:
            lines.append(f"**{pos.role_name}** (confidence: {pos.self_confidence:.2f}):")
            lines.append(pos.argument[:500])
            if pos.position_stability is not None:
                lines.append(f"  Position stability: {pos.position_stability:.2f}")
            lines.append("")

        # Agreement summary
        if round_result.agreement_matrix:
            avg_agree = _avg_agreement(round_result.agreement_matrix)
            lines.append(f"Average agreement: {avg_agree:.3f}")

        # Key disagreements
        for critique in round_result.critiques:
            if critique.points_of_disagreement:
                lines.append(
                    f"Disagreement ({critique.from_agent} vs {critique.to_agent}): "
                    + "; ".join(critique.points_of_disagreement[:3])
                )
        lines.append("")

    if debate_state.futility_flags:
        lines.append("### Futility Flags")
        for flag in debate_state.futility_flags:
            lines.append(f"- {flag}")
        lines.append("")

    return "\n".join(lines)


def _build_evidence_summary(evidence: list[EvidenceReport]) -> str:
    """Build a summary of research evidence for the synthesizer."""
    lines = []
    for report in evidence:
        lines.append(f"### {report.sub_question}")
        for finding in report.key_findings:
            lines.append(
                f"[{finding.epistemic_tag.value}] {finding.claim} "
                f"(relevance: {finding.relevance:.2f})"
            )
            for src in finding.sources:
                lines.append(f"  Source: {src.url}")
        if report.gaps:
            lines.append(f"Gaps: {report.gaps}")
        lines.append("")

    return "\n".join(lines) if lines else "No research evidence available."


def _parse_synthesis(
    response_text: str,
    brief: MissionBrief,
    debate_state: DebateState,
    evidence: list[EvidenceReport],
) -> FinalReport:
    """Parse the LLM's synthesis response into a FinalReport."""
    try:
        cleaned = response_text.strip()
        if cleaned.startswith("```"):
            lines = cleaned.split("\n")
            cleaned = "\n".join(lines[1:-1]) if len(lines) > 2 else cleaned

        data = json.loads(cleaned)

        # Parse key points
        key_points = []
        for kp_data in data.get("key_points", []):
            try:
                consensus_str = kp_data.get("consensus", "moderate").lower()
                try:
                    consensus = ConsensusLevel(consensus_str)
                except ValueError:
                    consensus = ConsensusLevel.MODERATE

                key_points.append(
                    KeyPoint(
                        point=kp_data.get("point", ""),
                        consensus=consensus,
                        evidence=kp_data.get("evidence", []),
                        dissent=kp_data.get("dissent"),
                    )
                )
            except Exception as e:
                logger.warning(f"Failed to parse key point: {e}")

        # Compute convergence score from last round
        convergence_score = 0.5
        if debate_state.rounds:
            last_round = debate_state.rounds[-1]
            convergence_score = _avg_agreement(last_round.agreement_matrix)

        return FinalReport(
            question=brief.question,
            complexity=brief.complexity,
            rounds_completed=len(debate_state.rounds),
            convergence_score=convergence_score,
            answer=data.get("answer", response_text[:2000]),
            key_points=key_points,
            dissenting_views=data.get("dissenting_views", []),
            research_sources=data.get("research_sources", []),
            futility_notes=data.get("futility_notes"),
        )

    except json.JSONDecodeError as e:
        logger.warning(f"Failed to parse synthesis JSON: {e}")
        return _fallback_report(brief, debate_state, evidence, "JSON parsing failed")


def _fallback_report(
    brief: MissionBrief,
    debate_state: DebateState,
    evidence: list[EvidenceReport],
    reason: str,
) -> FinalReport:
    """Generate a minimal fallback report when synthesis fails."""
    # Collect arguments from last round
    arguments = []
    if debate_state.rounds:
        last_round = debate_state.rounds[-1]
        for pos in last_round.positions:
            arguments.append(f"**{pos.role_name}**: {pos.argument[:300]}")

    answer = (
        f"# Synthesis Fallback\n\n"
        f"Synthesis generation failed ({reason}). "
        f"Below are the positions from the final debate round:\n\n"
        + "\n\n".join(arguments)
    )

    sources = []
    for report in evidence:
        for finding in report.key_findings:
            for src in finding.sources:
                sources.append(src.url)

    convergence_score = 0.5
    if debate_state.rounds:
        last_round = debate_state.rounds[-1]
        convergence_score = _avg_agreement(last_round.agreement_matrix)

    return FinalReport(
        question=brief.question,
        complexity=brief.complexity,
        rounds_completed=len(debate_state.rounds),
        convergence_score=convergence_score,
        answer=answer,
        key_points=[],
        dissenting_views=[],
        research_sources=sources,
        futility_notes=reason,
    )


def _build_pipeline_trace(
    brief: MissionBrief,
    evidence: list[EvidenceReport],
    debate_state: DebateState,
    synthesis_model: str,
    registry: ModelRegistry,
    synthesis_tokens: int,
) -> PipelineTrace:
    """Build the pipeline trace with per-role model usage."""
    usage = registry.get_usage()

    # Map usage to roles
    models_used = {}
    for model_id, model_usage in usage.items():
        # Determine role from model_id
        role = _infer_role(model_id, debate_state)
        models_used[role] = model_usage

    # Add synthesizer
    synth_model = registry.get(synthesis_model)
    models_used["synthesizer"] = ModelUsage(
        model=synthesis_model,
        family=synth_model.family if synth_model else "unknown",
        tokens=synthesis_tokens,
    )

    # Compute per-phase tokens
    scout_tokens = 0  # Tracked separately
    research_tokens = sum(r.tokens_used for r in evidence)
    debate_tokens = sum(
        tokens for role, mu in models_used.items()
        if role.startswith("debater") or role.startswith("nli_tier2")
        for tokens in [mu.tokens]
    )
    # If no debater usage tracked yet, estimate from state
    if debate_tokens == 0 and debate_state.rounds:
        debate_tokens = sum(
            tokens for mu in models_used.values() for tokens in [mu.tokens]
        ) - synthesis_tokens

    return PipelineTrace(
        models_used=models_used,
        scout_tokens=scout_tokens,
        research_tokens=research_tokens,
        debate_tokens=max(0, debate_tokens),
        synthesis_tokens=synthesis_tokens,
    )


def _infer_role(model_id: str, debate_state: DebateState) -> str:
    """Infer the role name for a model based on debate state."""
    # Simple heuristic: try to match model to roles
    for i, round_result in enumerate(debate_state.rounds):
        for pos in round_result.positions:
            # We can't directly map position to model, use agent_id
            pass
    return model_id.split("/")[-1].replace("-", "_").replace(".", "_")


def _avg_agreement(agreement_matrix: dict[str, dict[str, float]]) -> float:
    """Compute average agreement from the agreement matrix."""
    if not agreement_matrix:
        return 0.5

    scores = []
    for agent_id, others in agreement_matrix.items():
        for other_id, score in others.items():
            if agent_id < other_id:
                scores.append(score)

    return sum(scores) / len(scores) if scores else 0.5


def _generate_markdown(report: FinalReport) -> str:
    """Generate a complete markdown document from the report."""
    lines = []
    lines.append(f"# {report.question}")
    lines.append("")
    lines.append(f"**Complexity**: {report.complexity.value}")
    lines.append(f"**Rounds**: {report.rounds_completed}")
    lines.append(f"**Convergence**: {report.convergence_score:.2f}")
    lines.append("")
    lines.append(report.answer)
    lines.append("")

    if report.key_points:
        lines.append("## Key Points")
        lines.append("")
        for kp in report.key_points:
            consensus_emoji = {"strong": "✓", "moderate": "~", "contested": "✗"}
            lines.append(
                f"- [{kp.consensus.value}] {kp.point}"
            )
            if kp.dissent:
                lines.append(f"  - Dissent: {kp.dissent}")
        lines.append("")

    if report.dissenting_views:
        lines.append("## Dissenting Views")
        lines.append("")
        for dv in report.dissenting_views:
            lines.append(f"- {dv}")
        lines.append("")

    if report.research_sources:
        lines.append("## Sources")
        lines.append("")
        for src in report.research_sources:
            lines.append(f"- {src}")
        lines.append("")

    if report.futility_notes:
        lines.append("## Notes")
        lines.append("")
        lines.append(report.futility_notes)
        lines.append("")

    lines.append("## Pipeline Trace")
    lines.append("")
    trace = report.pipeline_trace
    lines.append(f"- Scout tokens: {trace.scout_tokens}")
    lines.append(f"- Research tokens: {trace.research_tokens}")
    lines.append(f"- Debate tokens: {trace.debate_tokens}")
    lines.append(f"- Synthesis tokens: {trace.synthesis_tokens}")
    lines.append(f"- Total tokens: {trace.total_tokens}")
    lines.append("")
    for role, mu in trace.models_used.items():
        lines.append(f"- {role}: {mu.model} ({mu.family}) — {mu.tokens} tokens")

    return "\n".join(lines)
