"""
Core type definitions for Deliberative Council.

All types are Pydantic models providing runtime validation, serialization,
and living documentation. Every module in the system depends on this file.
"""

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field


# ── Enums ──────────────────────────────────────────────────────────────


class Complexity(str, Enum):
    """Question complexity levels determined by Scout phase."""

    TRIVIAL = "trivial"  # Single model sufficient
    MODERATE = "moderate"  # Debate without research
    COMPLEX = "complex"  # Debate + research
    DEEP = "deep"  # Full pipeline, max rounds, extensive research


class ModelTier(str, Enum):
    """Model capability tier for cost-appropriate selection."""

    PREMIUM = "premium"
    MID = "mid"
    CHEAP = "cheap"


class EpistemicTag(str, Enum):
    """Epistemic status of a research finding."""

    SOURCED = "sourced"  # Directly traceable to a source URL
    INFERRED = "inferred"  # Synthesized from multiple sources
    JUDGMENT = "judgment"  # Agent's own assessment, no external source


class ConsensusLevel(str, Enum):
    """Consensus level for a key point in the final report."""

    STRONG = "strong"
    MODERATE = "moderate"
    CONTESTED = "contested"


class ResearchMode(str, Enum):
    """Research strictness mode."""

    STRICT = "strict"  # Only sourced findings included in debate context
    AUGMENTED = "augmented"  # All tag types allowed, clearly labeled


class ConvergenceReason(str, Enum):
    """Why the debate converged (or was terminated)."""

    ROUND_LIMIT_REACHED = "round_limit_reached"
    ROUND_LIMIT_BUT_DISAGREEMENT = "round_limit_but_disagreement"
    NLI_TIER1_CONVERGENCE = "nli_tier1_convergence"
    NLI_TIER2_CONVERGENCE = "nli_tier2_convergence"
    BUDGET_EXHAUSTED = "budget_exhausted"
    FUTILITY_DETECTED = "futility_detected"
    DEBATE_CONTINUING = "debate_continuing"


# ── Role & Mission ─────────────────────────────────────────────────────


class RoleSpec(BaseModel):
    """A debate role generated by the Scout phase."""

    name: str = Field(description="Role name, e.g. 'Skeptical Analyst'")
    perspective: str = Field(description="One-line perspective description")
    expertise: str = Field(description="Domain of expertise")
    suggested_model: str = Field(
        description="Model family hint (e.g. 'deepseek', 'anthropic')"
    )
    system_prompt: str = Field(description="Full system prompt generated by Scout")
    is_research: bool = Field(
        default=False, description="Whether this role is a research agent"
    )
    research_subquestion: str | None = Field(
        default=None, description="Sub-question for research focus"
    )


class MissionBrief(BaseModel):
    """Complete pipeline configuration produced by Scout phase.

    Note: token_budget applies to Research+Debate+Synthesis ONLY.
    Scout's own consumption is tracked separately.
    """

    question: str = Field(description="Original question (possibly rephrased)")
    complexity: Complexity = Field(description="Classified complexity level")
    domain_tags: list[str] = Field(
        default_factory=list, description="e.g. ['mathematics', 'logic', 'riddles']"
    )
    is_likely_solvable: bool = Field(
        description="Whether the question has a knowable answer"
    )
    why_might_be_hard: str = Field(description="Scout's reasoning about difficulty")
    suggested_roles: list[RoleSpec] = Field(
        description="Generated roles with full system prompts"
    )
    research_needed: bool = Field(description="Whether to activate research phase")
    research_subquestions: list[str] = Field(
        default_factory=list, description="Sub-questions for research agents"
    )
    debate_rounds: int = Field(
        ge=0, le=5, description="0 (trivial) to 3+ (deep)"
    )
    token_budget: int = Field(
        description="Budget for Research+Debate+Synthesis (excludes Scout)"
    )
    human_checkpoints: list[str] = Field(
        default_factory=list, description="Descriptions of points for human input"
    )
    scout_tokens_used: int = Field(
        default=0, description="Tokens consumed by the Scout phase (tracked separately)"
    )
    scout_reasoning: str = Field(description="Full reasoning trace from scout agent")
    verification_notes: str = Field(description="Notes from verification agent")


# ── Research ───────────────────────────────────────────────────────────


class EvidenceSource(BaseModel):
    """A single source for a research finding."""

    url: str
    snippet: str
    title: str


class ResearchFinding(BaseModel):
    """A single research finding with epistemic tag and multiple sources."""

    claim: str
    sources: list[EvidenceSource] = Field(
        description="Multiple sources per finding"
    )
    epistemic_tag: EpistemicTag = Field(
        description="Sourced, inferred, or judgment"
    )
    relevance: float = Field(ge=0.0, le=1.0, description="Relevance score")


class EvidenceReport(BaseModel):
    """Output of a single research agent."""

    agent_id: str = Field(description="Unique agent identifier")
    sub_question: str = Field(description="What was investigated")
    searches_performed: list[dict] = Field(
        default_factory=list, description="[{query, top_results}]"
    )
    key_findings: list[ResearchFinding] = Field(
        default_factory=list, description="Structured findings with tags"
    )
    gaps: str = Field(default="", description="What could not be found")
    recommended_investigation: str = Field(
        default="", description="What deeper search might reveal"
    )
    tokens_used: int = Field(default=0, description="Token consumption for budgeting")


# ── Debate ─────────────────────────────────────────────────────────────


class Position(BaseModel):
    """An agent's position in a single debate round."""

    agent_id: str
    role_name: str
    argument: str
    supporting_evidence: list[str] = Field(
        default_factory=list, description="Evidence cited"
    )
    self_confidence: float = Field(
        ge=0.0, le=1.0, description="Agent's self-reported confidence"
    )
    metacognitive_notes: str = Field(
        default="", description="Answer to 'what would change your position?'"
    )
    position_stability: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="NLI agreement with own previous position [0,1]; None for first round",
    )


class Critique(BaseModel):
    """An agent's critique of another agent's position."""

    from_agent: str
    to_agent: str
    points_of_agreement: list[str] = Field(default_factory=list)
    points_of_disagreement: list[str] = Field(default_factory=list)
    counter_arguments: list[str] = Field(default_factory=list)
    new_evidence: list[str] = Field(default_factory=list)


class BehavioralSignals(BaseModel):
    """Behavioral metrics computed for an agent after a round."""

    position_stability: float | None = Field(
        default=None, description="NLI agreement with own previous position"
    )
    evidence_novelty: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Fraction of evidence that is new this round",
    )
    majority_dependence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="How much position shifted toward group consensus without new evidence",
    )
    novelty_injection_triggered: bool = Field(
        default=False, description="Whether novelty injection was applied"
    )


class RoundResult(BaseModel):
    """Results of a single debate round."""

    round_number: int
    positions: list[Position] = Field(default_factory=list)
    critiques: list[Critique] = Field(default_factory=list)
    agreement_matrix: dict[str, dict[str, float]] = Field(
        default_factory=dict, description="Pairwise agreement scores"
    )
    nli_tier2_invoked: dict[str, dict[str, bool]] = Field(
        default_factory=dict, description="Whether Tier 2 was needed per pair"
    )
    behavioral_signals: dict[str, BehavioralSignals] = Field(
        default_factory=dict, description="Per-agent behavioral metrics"
    )


class ConvergenceResult(BaseModel):
    """Result of a convergence check."""

    converged: bool
    reason: ConvergenceReason
    details: str = Field(default="")


class FutilityCheck(BaseModel):
    """Result of a futility check."""

    is_futile: bool
    reason: str = Field(default="")
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)


class DebateState(BaseModel):
    """Complete state of an ongoing debate."""

    mission_brief: MissionBrief
    evidence_reports: list[EvidenceReport] = Field(default_factory=list)
    rounds: list[RoundResult] = Field(default_factory=list)
    communication_graph: dict[str, list[str]] = Field(
        default_factory=dict, description="Who sees whom"
    )
    futility_flags: list[str] = Field(default_factory=list)
    is_resolved: bool = Field(default=False)
    resolution_reason: str | None = Field(default=None)


# ── Agreement Analysis ─────────────────────────────────────────────────


class AgreementAnalysis(BaseModel):
    """Structured agreement analysis from NLI Tier 2."""

    substantively_agree: bool
    agreement_score: float = Field(ge=0.0, le=1.0)
    points_of_agreement: list[str] = Field(default_factory=list)
    points_of_disagreement: list[str] = Field(default_factory=list)
    is_fundamental_disagreement: bool = Field(
        default=False, description="Whether the disagreement is fundamental vs superficial"
    )
    summary: str = Field(default="")


# ── Final Report ───────────────────────────────────────────────────────


class KeyPoint(BaseModel):
    """A key finding from the debate with consensus assessment."""

    point: str
    consensus: ConsensusLevel
    evidence: list[str] = Field(default_factory=list, description="Source URLs")
    dissent: str | None = Field(
        default=None, description="Who disagrees and why"
    )


class ModelUsage(BaseModel):
    """Per-role model usage for cost attribution."""

    model: str
    family: str
    tokens: int


class PipelineTrace(BaseModel):
    """Complete pipeline execution trace."""

    models_used: dict[str, ModelUsage] = Field(
        default_factory=dict,
        description="Key: role id (e.g. 'scout', 'research_0', 'debater_1', 'synthesizer')",
    )
    scout_tokens: int = Field(default=0)
    research_tokens: int = Field(default=0)
    debate_tokens: int = Field(default=0)
    synthesis_tokens: int = Field(default=0)

    @property
    def total_tokens(self) -> int:
        return self.scout_tokens + self.research_tokens + self.debate_tokens + self.synthesis_tokens


class FinalReport(BaseModel):
    """The final output of the Deliberative Council."""

    question: str
    complexity: Complexity
    rounds_completed: int
    convergence_score: float
    answer: str = Field(description="Main synthesized answer (markdown)")
    key_points: list[KeyPoint] = Field(
        default_factory=list, description="Structured findings with consensus"
    )
    dissenting_views: list[str] = Field(
        default_factory=list, description="Unresolved disagreements"
    )
    research_sources: list[str] = Field(
        default_factory=list, description="All source URLs"
    )
    pipeline_trace: PipelineTrace = Field(
        default_factory=PipelineTrace, description="Cost and model tracking"
    )
    futility_notes: str | None = Field(default=None)
    human_input_requested: bool = Field(default=False)
    human_input: str | None = Field(default=None)
    raw_markdown: str = Field(default="", description="Complete markdown for export")


# ── Model Registry Types ──────────────────────────────────────────────


class ModelInfo(BaseModel):
    """Information about an available model."""

    model_id: str = Field(description="LiteLLM model identifier, e.g. 'openrouter/meta-llama/llama-3.3-70b-instruct:free'")
    family: str = Field(description="Model family, e.g. 'openai', 'anthropic'")
    tier: ModelTier = Field(description="Capability tier")
    context_window: int = Field(description="Maximum context window in tokens")
    input_cost_per_m: float = Field(default=0.0, description="Input cost per million tokens")
    output_cost_per_m: float = Field(default=0.0, description="Output cost per million tokens")
    supports_local: bool = Field(default=False, description="Whether available via Ollama")
    is_available: bool = Field(default=True, description="Whether currently reachable")

    # Provider routing (for Cloudflare, custom endpoints)
    provider: str = Field(default="", description="Provider name, e.g. 'cloudflare', 'openrouter'")
    api_base: str = Field(default="", description="Custom API base URL (env-expanded)")
    api_key: str = Field(default="", description="API key (env-expanded)")
    conserve: bool = Field(default=False, description="True if credits are non-regenerating")
    geo_blocked: bool = Field(default=False, description="True if provider is geo-blocked from this server")
    canonical_id: str = Field(default="", description="Canonical model ID for cross-provider dedup (e.g. 'llama-3.3-70b')")
    rpm: int = Field(default=20, description="Requests per minute limit")
    daily_quota: int = Field(default=0, description="Daily request quota (0=unlimited)")
    regenerates: bool = Field(default=True, description="Whether daily quota regenerates")


class HealthCheckResult(BaseModel):
    """Result of a model provider health check."""

    model_id: str
    is_healthy: bool
    latency_ms: float | None = Field(default=None)
    error: str | None = Field(default=None)


# ── Provider Info ──────────────────────────────────────────────────────


class ProviderInfo(BaseModel):
    """Metadata about an LLM provider (from the providers: section of providers.yaml).

    Used for:
    - Cross-provider fallback awareness (same model on different providers)
    - Quota tracking (daily_quota, regenerates, conserve flag)
    - Geo-blocking awareness
    - Priority ordering
    """

    name: str = Field(description="Provider name, e.g. 'cloudflare', 'openrouter'")
    priority: int = Field(default=0, description="Lower = preferred. 0 = highest priority")
    env_key: str = Field(default="", description="Environment variable name for API key")
    regenerates: bool = Field(default=True, description="Whether daily quota regenerates")
    daily_quota: int = Field(default=0, description="Daily request quota (0=unlimited)")
    rpm: int = Field(default=20, description="Requests per minute limit")
    geo_blocked: bool = Field(default=False, description="Whether provider is geo-blocked from this server")
    conserve: bool = Field(default=False, description="True if credits are non-regenerating")
    api_base_template: str = Field(default="", description="API base URL template with {ENV_VAR} placeholders")
    notes: str = Field(default="", description="Human-readable notes")
